<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>ModioModNetworker</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Resources\networkermenu.android.networker" />
    <None Remove="Resources\networkermenu.networker" />
    <EmbeddedResource Include="Resources\networkermenu.android.networker" LogicalName="ModioModNetworker.Resources.networkermenu.android.networker" />
    <EmbeddedResource Include="Resources\networkermenu.networker" LogicalName="ModioModNetworker.Resources.networkermenu.networker" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="MelonLoader" HintPath="/mnt/d/SteamLibrary/steamapps/common/BONELAB/MelonLoader/net6/MelonLoader.dll" />
    <Reference Include="LabFusion" HintPath="/mnt/d/SteamLibrary/steamapps/common/BONELAB/Mods/LabFusion.dll" />
    <Reference Include="Il2CppSLZ.Marrow" HintPath="/mnt/d/SteamLibrary/steamapps/common/BONELAB/MelonLoader/Il2CppAssemblies/Il2CppSLZ.Marrow.dll" />
    <Reference Include="UnityEngine.CoreModule" HintPath="/mnt/d/SteamLibrary/steamapps/common/BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.CoreModule.dll" />
    <Reference Include="Unity.TextMeshPro" HintPath="/mnt/d/SteamLibrary/steamapps/common/BONELAB/MelonLoader/Il2CppAssemblies/Unity.TextMeshPro.dll" />
    <Reference Include="UnityEngine.UI" HintPath="/mnt/d/SteamLibrary/steamapps/common/BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.UI.dll" />
    <Reference Include="UnityEngine.AnimationModule" HintPath="/mnt/d/SteamLibrary/steamapps/common/BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.AnimationModule.dll" />
    <Reference Include="UnityEngine.PhysicsModule" HintPath="/mnt/d/SteamLibrary/steamapps/common/BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.PhysicsModule.dll" />
    <Reference Include="UnityEngine.AssetBundleModule" HintPath="/mnt/d/SteamLibrary/steamapps/common/BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.AssetBundleModule.dll" />
    <Reference Include="Unity.ProBuilder" HintPath="/mnt/d/SteamLibrary/steamapps/common/BONELAB/MelonLoader/Il2CppAssemblies/Unity.ProBuilder.dll" />
    <Reference Include="BoneLib" HintPath="/mnt/d/SteamLibrary/steamapps/common/BONELAB/Mods/BoneLib.dll" />
    <Reference Include="Il2Cppmscorlib" HintPath="/mnt/d/SteamLibrary/steamapps/common/BONELAB/MelonLoader/Il2CppAssemblies/Il2Cppmscorlib.dll" />
    <Reference Include="UnityEngine.UnityWebRequestModule" HintPath="/mnt/d/SteamLibrary/steamapps/common/BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.UnityWebRequestModule.dll" />
    <Reference Include="0Harmony" HintPath="/mnt/d/SteamLibrary/steamapps/common/BONELAB/MelonLoader/net6/0Harmony.dll" />
    <Reference Include="UnityEngine.UnityWebRequestTextureModule" HintPath="/mnt/d/SteamLibrary/steamapps/common/BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.UnityWebRequestTextureModule.dll" />
    <Reference Include="Newtonsoft.Json" HintPath="/mnt/d/SteamLibrary/steamapps/common/BONELAB/MelonLoader/net6/Newtonsoft.Json.dll" />
    <Reference Include="Unity.ResourceManager" HintPath="/mnt/d/SteamLibrary/steamapps/common/BONELAB/MelonLoader/Il2CppAssemblies/Unity.ResourceManager.dll" />
    <Reference Include="Il2CppInterop.Runtime" HintPath="/mnt/d/SteamLibrary/steamapps/common/BONELAB/MelonLoader/net6/Il2CppInterop.Runtime.dll" />
    <Reference Include="UnityEngine.UIModule" HintPath="/mnt/d/SteamLibrary/steamapps/common/BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.UIModule.dll" />
    <Reference Include="Unity.Addressables" HintPath="/mnt/d/SteamLibrary/steamapps/common/BONELAB/MelonLoader/Il2CppAssemblies/Unity.Addressables.dll" />
    <Reference Include="Il2CppSystem" HintPath="/mnt/d/SteamLibrary/steamapps/common/BONELAB/MelonLoader/Il2CppAssemblies/Il2CppSystem.dll" />
    <Reference Include="Il2CppSystem.Core" HintPath="/mnt/d/SteamLibrary/steamapps/common/BONELAB/MelonLoader/Il2CppAssemblies/Il2CppSystem.Core.dll" />
    <Reference Include="Il2CppInterop.Common" HintPath="/mnt/d/SteamLibrary/steamapps/common/BONELAB/MelonLoader/net6/Il2CppInterop.Common.dll" />
    <Reference Include="UnityEngine.UnityWebRequestWWWModule" HintPath="/mnt/d/SteamLibrary/steamapps/common/BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.UnityWebRequestWWWModule.dll" />
    <Reference Include="UnityEngine.InputLegacyModule" HintPath="/mnt/d/SteamLibrary/steamapps/common/BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.InputLegacyModule.dll" />
    <Reference Include="UnityEngine.TextRenderingModule" HintPath="/mnt/d/SteamLibrary/steamapps/common/BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.TextRenderingModule.dll" />
    <Reference Include="UnityEngine.InputModule" HintPath="/mnt/d/SteamLibrary/steamapps/common/BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.InputModule.dll" />
    <Reference Include="UnityEngine.ImageConversionModule" HintPath="/mnt/d/SteamLibrary/steamapps/common/BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.ImageConversionModule.dll" />
    <Reference Include="UnityEngine.IMGUIModule" HintPath="/mnt/d/SteamLibrary/steamapps/common/BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.IMGUIModule.dll" />
    <Reference Include="UnityEngine.JSONSerializeModule" HintPath="/mnt/d/SteamLibrary/steamapps/common/BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.JSONSerializeModule.dll" />
    <Reference Include="UnityEngine.UnityWebRequestAudioModule" HintPath="/mnt/d/SteamLibrary/steamapps/common/BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.UnityWebRequestAudioModule.dll" />
    <Reference Include="UnityEngine.ParticleSystemModule" HintPath="/mnt/d/SteamLibrary/steamapps/common/BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.ParticleSystemModule.dll" />
    <Reference Include="UnityEngine.AudioModule" HintPath="/mnt/d/SteamLibrary/steamapps/common/BONELAB/MelonLoader/Il2CppAssemblies/UnityEngine.AudioModule.dll" />
    <Reference Include="Il2CppUniTask" HintPath="/mnt/d/SteamLibrary/steamapps/common/BONELAB/MelonLoader/Il2CppAssemblies/Il2CppUniTask.dll" />
  </ItemGroup>
</Project>